services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_API: ${NEXT_PUBLIC_API}
        NEXT_PUBLIC_REVERB_APP_KEY: ${NEXT_PUBLIC_REVERB_APP_KEY}
        NEXT_PUBLIC_REVERB_HOST: ${NEXT_PUBLIC_REVERB_HOST}
        NEXT_PUBLIC_REVERB_PORT: ${NEXT_PUBLIC_REVERB_PORT}
        NEXT_PUBLIC_REVERB_SCHEME: ${NEXT_PUBLIC_REVERB_SCHEME}
    env_file:
      - .env.local
    ports:
      - "${APP_PORT:-3000}:3000"
    restart: unless-stopped
